
main: main.c util.h util.c file.h file.c log.h log.c page.h page.c table.c table.h tx.h tx.c db.h db.c
	gcc -std=c11 main.c file.c util.c log.c page.c table.c tx.c db.c -o main -pthread -g

clean:
	rm -rf students log
